config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'home', to: 'tweets#index'
  resources :tweets, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :set_tweet, only: [:show]

    def index
        @tweets = Tweet.all
    end

    def show
    end

    def new
        @tweet = Tweet.new
    end 

    def create
        @tweet = Tweet.new(tweet_params)
        if @tweet.save
            flash[:notice] = "Tweet Posted!"
            redirect_to home_path
        else 
            render :new, status: :unprocessable_entity
        end
    end

    private

    def tweet_params
        params.require(:tweet).permit(:description)
    end

    def set_tweet
        @tweets = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true) do |x| %>
<br>
    <div>
        <div> 
            <%=x.label :description, "Tweet" %> 
            <div>
                <%= x.text_field :description, palceholder: "Tweeet something" %>
            </div>
        </div>

        <div>
        <%= x.submit %>
        </div>
        
    </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div>
    <% @tweets.each do |x| %>
        <div>  <%= x.description %> </div>
    <% end %>
</div>

app/views/tweets/index.html.erb
<h1> Home Page </h1>


<%= render 'tweet'%>

<div>
    <%= button_to "New Tweet", new_tweet_path, method: :get, class: "bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded" %>
</div>

app/views/tweets/new.html.erb
<h1> New Tweet <h1>

<%= render 'form' %>